{% set name = "nest-desktop" %}
{% set version = "3.2.0rc2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 829c85b13e2bff57a3f7ba635c0653550b72f1e7d2f4c50cb814464688920ace

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  imports:
    - nest_desktop
  commands:
    - pip check
    - nest-desktop status  # [unix]
  requires:
    - pip

about:
  home: https://github.com/nest-desktop/nest-desktop
  summary: A web-based GUI application for NEST Simulator
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/nest-desktop/nest-desktop
  doc_url: https://nest-desktop.readthedocs.io
  doc_source_url: https://github.com/nest-desktop/nest-desktop/blob/master/README.rst

extra:
  recipe-maintainers:
    - babsey
