{% set name = "nest-desktop" %}
{% set version = "3.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e418ed1f6d8a392284795949075e34019ae763b01757ac007f7b8acbfccdabd7

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  imports:
    - nest_desktop
  commands:
    - pip check
    - nest-desktop status  # [unix]
  requires:
    - pip

about:
  home: https://github.com/nest-desktop/nest-desktop
  license: MIT
  license_file: LICENSE
  summary: NEST Desktop is a web-based application for NEST Simulator.
  description: |
    NEST Desktop is a web-based application which provides a graphical user interface for NEST Simulator. With this
    easy-to-use tool, users can interactively construct neuronal networks and explore network dynamics. Advanced users
    often choose NEST Simulator: a prominent tool for spiking neuronal networks to measure network dynamics. However,
    programming knowledge is required to write code for this tool. NEST Desktop bypasses this requirement, but still
    teaches users how to construct and explore neuronal networks. A textual script is generated from the constructed
    networks and sent to NEST Simulator; the network activity is then visualized in a graph or table. It is a useful
    teaching tool, since the network graphs and network activity visualizations can be exported to files that users can
    implement for their course protocol.
  dev_url: https://github.com/nest-desktop/nest-desktop
  doc_url: https://nest-desktop.readthedocs.io
  doc_source_url: https://github.com/nest-desktop/nest-desktop/blob/master/README.rst

extra:
  recipe-maintainers:
    - babsey
